<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Font\ElaAwesome.ttf" />
    <None Remove="Font\FontAwesome.otf" />
    <None Remove="Font\iconfont.ttf" />
    <None Remove="Font\visionicon.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Font\ElaAwesome.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Font\FontAwesome.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Font\iconfont.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Font\visionicon.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Converter\" />
  </ItemGroup>

</Project>
